[package]
name = "telegram-cache-decrypt"
version = "0.1.0"
authors = ["iovxw <iovxw@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aes-ctr = "0.3"
